### ISSUE TITLE
Boss reward streaks

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#102]
[Telos](https://runescape.wiki/w/Telos,_the_Warden) in RS3 has this interesting mechanic where once killed you get the option to take your reward, or leave it, if left it increase the chance of a rare reward for the next kill but also makes the boss harder. If you die you loose your streak and a % of the rewards saved are reclaimed.

**Comment by kiairatech** [comment]
I like the idea of leaving loot for an increased chance at the next drop from the same npc. This should definitely have a cap and a minimal increase per kill [based on the npc combat level maybe.

**Comment by GregHib** [comment]
Yeah probably not a good idea to do for everything, just for one or two bosses
