### ISSUE TITLE
Decide why player ids are needed, and redesign sql loading

### ISSUE THREAD

**Issue by kiairatech** [dusk-rs/dusk#106]
https://github.com/dusk-rs/dusk/blob/8f298596387c2911537b108ac77f290baf8e9f15/engine/src/main/kotlin/rs/dusk/engine/data/sql/SQLPlayerStorage.kt#L46

**Comment by GregHib** [comment]
Unique player id is needed for database relationships, unless you intend to do database searches using a string for login-name.
The id has to be stored in the player model to look up other data, and so it isn't lost (and two players created) when switching between sql and local yml
