### ISSUE TITLE
Clarification is needed on the purpose of the cache delegate

### ISSUE THREAD

**Issue by kiairatech** [dusk-rs/dusk#113]
https://github.com/dusk-rs/dusk/blob/cbcec6a48bf0855464bc8fe6651a27d0323ccf6d/cache/src/main/kotlin/rs/dusk/cache/CacheDelegate.kt#L19

**Comment by GregHib** [comment]
Delegation loosens the dependency on Displee's cache lib. Meaning if we were to update to a version with breaking changes or switch to a different library entirely, we only have to change the delegate rather than every place the cache is in use.
