### ISSUE TITLE
Event precursors and successors need reconsideration

### ISSUE THREAD

**Issue by kiairatech** [dusk-rs/dusk#117]
Example: a player clicks a tile to walk on. The event system must be able to stop the event from executing as well as notify the bus after it executed.

What this requires is a method to ensure that everything bound to the event has validated that it should proceed.

**Comment by GregHib** [comment]
The example isn't very clear, why would such an event need cancelling?

**Comment by kiairatech** [comment]
Aside from the example the functionality is a necessity.

**Comment by GregHib** [comment]
> Aside from the example the functionality is a necessity.

But I don't understand why

**Comment by kiairatech** [comment]
I'll provide an anecdote:

When a player is jumping the ditch in edgeville and they try to drink a potion, teleport, or perform another task, there's a message that says "you can't do this right now" (or something along those lines). 

This is why it's necessary; if we don't have this functionality for events we have to use handlers with multiple if statements, which is contrary to the design. 


At the time of writing this I'm at work but I hope I explained it well.
