### ISSUE TITLE
Performant data storage solution

### ISSUE THREAD

**Issue by kiairatech** [dusk-rs/dusk#12]
Can be split into four types of data (persistent is 2 in 1):
- [x] Temporary #20 - direction facing, uptime, update countdown
- [ ] Persistent data  #18
- [x] Immutable data #19

**Comment by Tyluur** [comment]
The data storage solution needs to be able to:

1) Represent data in a separate model from the way it is written in OOP
2) Offer data manipulation easily

Am I missing anything? I'm at the start of writing the code with Exposed + HikariCP [64b7ff4a26dd03aa74bdc7c88356379da3497db6]

**Comment by GregHib** [comment]
> 1. Represent data in a separate model from the way it is written in OOP

Doesn't _need_ to be, but might in places. e.g banking. In other places, e.g CharacterValues, you'll *have* to represent it the same unless you want a massive migraine

**Comment by Tyluur** [comment]
Isn't CharacterValues mapping from a String to an Object?

**Comment by GregHib** [comment]
> Isn't CharacterValues mapping from a String to an Object?

Yep but it'll be much easier just to store the whole map (perhaps change it from `Map<String, Any>` to `Map<String, Seralizable>` if necessary) than to write custom savers for what'll be hundreds of values
