### ISSUE TITLE
NPC Spawns

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#121]
Jagex dumpped the surface world npc spawns for the osrs wiki
https://runescape.wiki/w/User:Shaunypwns/DoogleMaps/NPCData
Saved:
[OSRS NPC Dump.txt](https://github.com/dusk-rs/dusk/files/4742822/OSRS.NPC.Dump.txt)

**Comment by GregHib** [comment]
How this should be parsed:
* Compare names and npc id's with npc definitions - highlighting and manually fixing differences
* Parse npc definitions for unwalkable npcs, and manually add facing directions
* Parse coordinates and highlight any that are in regions without maps

**Comment by kiairatech** [comment]
Exactly! Love this release.
