### ISSUE TITLE
Area of effect looting

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#136]
A walkable container interface which shows all nearby floor items that you can click to loot to inventory, or a button to loot all

**Comment by GregHib** [comment]
3x3 area seems reasonable.
Would need consideration what applies, could be abused but picking up items which wouldn't normally be reachable (on other side of walls) and things like drop parties where it'd just be a spam button, could only apply to drops of mobs you have damaged.

**Comment by Tyluur** [comment]
Good idea, everything within reachable distance of the player sounds fair. I see this being used for picking up loot around monster's you've recently killed.
