### ISSUE TITLE
Updating staggered addition fix

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#145]
There's a 1 tick delay when entering and exiting view distance from another player or npc for them to be added or removed.

Consequence: 
* when removing a character appears at the wrong location for 1 tick
* when adding a character they're invisible for a 1 tick

**Comment by GregHib** [comment]
Appears to be an order issue, as inbound packets aren't buffered and processed before movement the next update will nearly always be the tick after rather than the current one. Should be fixed by #157

**Comment by Tyluur** [comment]
https://gist.github.com/GregHib/a464ea0e5c14925d1e32965d2dc543e8
