### ISSUE TITLE
File-server message batching

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#159]
Scu11
i process clients in batches
so i serve 20 assets to one client, then move onto the next
readding my client to the end of the queue if i have more to request
i found that batching the requests helped with transfer times
the "Js5Client"s are in a kotlin Channel
i take the first one from the channel
process 20 of their requests
add them back to the channel if they still have more to request
rinse and repeat

**Comment by Tyluur** [comment]
So essentially cap the amount of js5 requests that can be processed in a separate worker. Sounds like a good countermeasure.

**Comment by GregHib** [comment]
> 
> 
> So essentially cap the amount of js5 requests that can be processed in a separate worker. Sounds like a good countermeasure.

Yeah, continuiously switch between who's requests to process.

Currently if you open two clients at the same time, the second won't start loading until the first is completed.
