### ISSUE TITLE
System Data Storage

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#18]
Rather than a player centric storage solution, storing data per system will be far more flexible. There is the question of how to represent this as systems will vary and should be independent from one another.

Can be split into two further categories:
* Session base - Skills, timers/effects
* Session independent - Display name, friends/clan chat settings, G.E

**Comment by GregHib** [comment]
## Direct Access
```kotlin
player.inventory()
player.bank()
player.equipment()
player.bob()
```
### Pros
* Easier to find the method you're after
### Cons
* Lots of boiler plate
* Not easily extensible

**Comment by GregHib** [comment]
## Indirect Access
```kotlin
sealed class Container(id: Int) {
    object Inventory : Container(93)
}
player.container(Inventory)
player.container(Bank)
player.container(Equipment)
player.container(Bob)
```
### Pros
* One method to rule them all
### Cons
* Not as intuitive to use

**Comment by GregHib** [comment]
# idea
StorageSystem injected in, used to load and save data, or register savable data.

Data is binded to POKO

**Comment by GregHib** [comment]
How to save data in systems such as `TileSystem` where only player tiles need saving?

Potential solution: On entity deregister save only if is `Player`. Doesn't solve non-logout saving however.

**Comment by GregHib** [comment]
As player data class is in use it must have been decided otherwise.

**Comment by GregHib** [comment]
Still necessary but needs more thought into how

**Comment by GregHib** [comment]
Line needs to be drawn somewhere

Single barrows counter variable should be persistent in CharacterValues
_Some_ large quantity of related other data should go in it's own data class e.g achievements

**Comment by Tyluur** [comment]
I think the most optimal solution will cover the following topics:

1) Separation of database storage model from OOP practices
2) Simple database operations 
3) Data accuracy (transactions)
4) Testability

Exposed & HikariCIP seem to be the most feasible solutions
