### ISSUE TITLE
Design entity hierarchy/relationships

### ISSUE THREAD

**Issue by kiairatech** [dusk-rs/dusk#2]
```kotlin
interface Node {
    val id: Int // Type id for most entities, index for players
}
interface Entity : Node {
    var tile: Tile
}
```

How much information should a entity class store vs what a system should store?

**Comment by GregHib** [comment]
Decided that `Node` isn't necessary. Although questionable for Projectiles whether they need the inital spawn tile saved incase a new player comes into view or not. For now stick with `Entity` with id & tile, inherited by Player, Npc, Obect, Floor Item & Projectile
