### ISSUE TITLE
Consider individual entity event bus

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#206]
It's come up while implmenting "following" that one player might be interested when a particular entity does a particular action.

e.g "when the player I'm following teleports". The current system allows listening to an event at a global level, which can be filtered down to an individual level however there's no way of linking the two players without having some kind of "players following me" list.

The implementation would be a simplified version; option to add or remove a listener, a "one time use" or "temp" listener would also be useful.
**No filters or priorities.**

```kotlin
val listeners = Map<EventCompanion<out PlayerEvent>, MutableList<EventListener>>

data class EventListener<T : Event>(val block: (T) -> Unit, val temp: Boolean = false)
````

The current event bus could simply call at the end "if entity event, entity.emit(event)"

**Comment by GregHib** [comment]
Expected use for following

```kotlin
val cancel = { player.action.cancel() }
player.watch(target)
target.on(Teleport, cancel)
target.on(Logout, cancel)
player.action {
    try {
        while(delay() && isActive) {
            pf.find(player, target)
        }
    } finally {
        player.watch(null)
        target.remove(cancel)
    }
}
```

Does question whether we want to listen for Event's or Actions. Or both.

```kotlin
target.on(Moved) {
    if(target.moveType == Teleport) {
        player.action.cancel()
    }
}
```

Assisting might also be a fitting use case. Rather than store "assisted"/"assistent"

**Comment by Tyluur** [comment]
I think you're addressing the issue in reverse. If a player teleports and they have n players following them, we should execute an event [or transmit a message] to stop all of the involved players from following player.

**Comment by GregHib** [comment]
> I think you're addressing the issue in reverse. If a player teleports and they have n players following them, we should execute an event [or transmit a message] to stop all of the involved players from following player.

You'd then need to identify the followers, e.g

```kotlin
StopFollowingMe then {
    players.filter { it.isFollowing(player) }
}
```

Which is at worst O(n), or at best a stored list of players.
>however there's no way of linking the two players without having some kind of "players following me" list

Also doesn't address scenario's like #189, where `Moved` already exists. You'd need a "players walking towards me" list, same goes for "players attacking me"; every scenario would need it's own list.

**Comment by Tyluur** [comment]
I see what you're saying. Perhaps then we should have a precursor for actions to remain live. In the case of following, we'd assume the player is in the same region.

**Comment by GregHib** [comment]
Implemented this, but soon after realised it's not the way to go. The things that needed detecting; Movement, Teleport & Logout should all be actions and after a few action system modifications can now be checked for as so.

Why this idea didn't work in practise:
Quick and dirty solution - Individual variable listanable properties would be a better solution See; JavaFX (But would be a lot of big changes to things like updating)
Concurrent modification exceptions when adding and removing listeners
