### ISSUE TITLE
GameObject width and height needs to take rotation into account

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#217]
gameObject.size doesn't take rotation into account.
The calculation on whether to flip width and height is:
```kotlin
val flip = rotation and 0x1 == 1
```

> Watch out for existing usages which already flip as they will conflict!

**Comment by Tyluur** [comment]
I'm not sure addressing this in the size variable would be as valuable as using the tiles the object is existent on.

**Comment by GregHib** [comment]
> I'm not sure addressing this in the size variable would be as valuable as using the tiles the object is existent on.

Everywhere width/height is used so is this alg to compensate for rotation. Original sizeX and sizeY can still be obtained from object definitions if needed

**Comment by Tyluur** [comment]
The OP confused me a bit, I get what you're saying now. Good thinking.
