### ISSUE TITLE
When the game is still loading essentials, players should receive an update is in progress message on login.

### ISSUE THREAD

**Issue by kiairatech** [dusk-rs/dusk#28]

**Comment by GregHib** [comment]
Related to #68

**Comment by JacobRhiel** [comment]
Would it be more beneficial to not allow incoming connections until assets are loaded, or not bind the channel until they are?

**Comment by GregHib** [comment]
Yep that would be the simplier solution, I thought that's how it was but turns out otherwise; just moving `server.run()` to the last thing should do the trick
