### ISSUE TITLE
Dialogues

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#82]
Dependent on Queue #8

**Comment by kiairatech** [comment]
I don't think dialogues are dependent on #8 - they're another form of a queue being used for the most dominant dialogue. Otherwise dialogues would have to have multiple priority possibilities.

**Comment by GregHib** [comment]
Yeah could be, needs discussion if there is a use-case where dialogue needs to stack more than 2 and so needs to use it's own queue, rather than handled by the Queuing system itself

**Comment by kiairatech** [comment]
> Yeah could be, needs discussion if there is a use-case where dialogue needs to stack more than 2 and so needs to use it's own queue, rather than handled by the Queuing system itself

Skill dialogues for example as a use case which would be beneficial to have a chain/queue of dialogues to show. Take for example you do ::master and get 14M experience in every skill. The usual functionality is that only the most recent level-up skill dialogue is shown, but on RS when you level more than 1 skill at a time, the dialogues chain.

**Comment by GregHib** [comment]
There will need to be a priority order too as some dialogues are more important and display over others. Also the Queue supports waiting for an interface to close before doing something, isn't there a scenario where that something is a dialogue?
