### ISSUE TITLE
Content Longevity

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#88]
Players typically expect the ability to wield all items shortly after joining, with high xp rates or cheap items. Giving a balance of 90% of content accessible straight away and 10% needing to be obtained through boss drop. There's a number of issues with that:

## Longevity
Players need the "what's next" to keep playing.
* Level to get
* Item to obtain
* Boss to kill
* Time to beat
* Goal
* Achivement
* Outfit
etc...
By giving 90% of content up-front (or within first few hours/days/weeks), players run out of things to do (end-game) and move on to another server (churn). This also puts pressure on devs to put out content quickly and unsustainably as end-game players will often complete content faster than it takes a dev to build. Also there's limited room for sense of improvement, No player is going to be in iron oogling over a guy in addy. It's paid for, max gear, or nothing.

### Changing exp rates
Low exp rates - Server lasts longer, lots of players don't like
Multiple game-modes/prestiging - overdone, bad attempt at re-playability, would need more variation between modes/prestiges to keep the game fresh. Lots of pre-conseived opinions about "x10, x25, x100".
Custom xp curve - Haven't seen done a lot, would give a new feel to the game, could make it much flatter of a curve, maybe make lvl 75/80 half way between 0-99 instead of 92.

### New equipment requirements
Linking achievements with equipment requirements would limit how quickly players progress, gives players a new challenge to obtain amours (instead of typical, rock crabs for 10 mins), changing up what items other players are seen using (max cape player using mith to get achievements for comp cape), and giving a better sense of achievement to players for wearing armour.

Whatever the solution there is going to be a sub-group of players which won't like it and call it stupid that they don't get everything they want easily. I think we should categorise these players as "spoiled babies" and the response to them should always be; tough it's better for everyone.

**Comment by kiairatech** [comment]
If we look at servers that been successful, we can create some assessment of why they've been successful.

**Alotic**
- Low experience rates & drop rates
- highly active pking (including a clanning community
- relatively friendly community
- hd graphics

**Alora**
- Frequent content updates to follow the timeline of RuneScape
- low experience rates and drop rates
- RuneScape client offered in osrs and HD graphics

I'm sure we can look at other examples of servers, but in my opinion, if we can offer game content for both osrs and 2011 in a way that end-game content will take a long time for layers to achieve, we'll capture a large player base.

One other important thing to note is that we need to have an active wilderness. This can be done with some incentives for wilderness activity, as well as perhaps bounty hunter 2 (from OSRS). I had also been remembering the old bounty hunter minigame that was in RS2008 (https://www.youtube.com/watch?v=Cab91hplOkY).
But this would take from activity in the wilderness, so perhaps a custom version of it? Just a thought.

**Comment by kiairatech** [comment]
To add onto the _longevity_ note, having items that can only be received from points/minigames/etc. can add onto the end-game content. Rares being received from this way would be one idea; OSRS has no value for rare items anymore.

**Comment by GregHib** [comment]
> To add onto the _longevity_ note, having items that can only be received from points/minigames/etc. can add onto the end-game content. Rares being received from this way would be one idea; OSRS has no value for rare items anymore.

Yes, end game always comes down to rares (pets in osrs) and achievements, in most server's once they're done it's game over for that player and they either quit or start over. Really hard to achieve rewards are necessary to keep even the most veteran player working to something
