### ISSUE TITLE
Does movement need suspending until region has finished loading?

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#93]
Scenarios:

Client moves during region load causing regions to be out of sync
Server region collision map takes a long time or fails to load. 
Client fails to send a "region loaded" response message

Should the player be frozen, movement commands be buffered, or what while a region is loading either server or client side?

**Comment by GregHib** [comment]
Movement must be stopped while the client is loading a new region otherwise the client region can get out of sync. This was addressed in b79edb9.

However there is no support added for waiting for collision maps to load server side. This will work without presuming the time to load the collision map (typically < 100ms) is less than time for the client to load the region and receive the update packet (600ms).
Could potentially cause movement requests to be ignored as an unloaded collision map by default always collides but won't fix unless occurs.

**Comment by kiairatech** [comment]
> Movement must be stopped while the client is loading a new region otherwise the client region can get out of sync. This was addressed in [b79edb9](https://github.com/dusk-rs/dusk/commit/b79edb99023134b16455dbab60562619463a7abc).
> 
> However there is no support added for waiting for collision maps to load server side. This will work without presuming the time to load the collision map (typically < 100ms) is less than time for the client to load the region and receive the update packet (600ms).
> Could potentially cause movement requests to be ignored as an unloaded collision map by default always collides but won't fix unless occurs.

When a player enters a region, the server should load more regions around it, to reduce the likelihood of this happening.

**Comment by GregHib** [comment]
> When a player enters a region, the server should load more regions around it, to reduce the likelihood of this happening.

Yeah it does that already, still as risk when it comes to teleporting in to a new region.
