### ISSUE TITLE
Improve entity factories after more are in use

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#98]
Are they necessary?
Should Registered be emitted from within them?
See 4ce985c6cd36375e61766aaf5ce888b5f23adfbc

**Comment by kiairatech** [comment]
Sidenote: player is the only entity which you need to save, the rest are constructed by factories

**Comment by GregHib** [comment]
> player is the only entity which you need to save

However not the only one loaded from save file(s) if that's the direction we're going. Floor item spawns & NPC spawns.

**Comment by GregHib** [comment]
All entity factories now removed in favour of Events with return types c052a86f1081f5c42a2829f990b35e7019459692
